package main.java;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'webonise' at '22/8/16 12:44 PM' with Gradle 3.0
 *
 * @author webonise, @date 22/8/16 12:44 PM
 */
public class QuickSort
{
	 int array[];

	 public QuickSort(int [] input,int length){
			array=new int[length];
			array=input;
		}
    int partition(int low, int high)
    {
        int pivot = array[high]; 
        int i = (low-1); 
        for (int j=low; j<=high-1; j++)
        {
            if (array[j] <= pivot)
            {
                i++;
                int temp = array[i];
                array[i] = array[j];
                array[j] = temp;
            }
        }
 
        int temp = array[i+1];
        array[i+1] = array[high];
        array[high] = temp;
 
        return i+1;
    }
 
    void sort( int low, int high)
    {
        if (low < high)
        {
            int pi = partition(low, high);
            sort( low, pi-1);
            sort( pi+1, high);
        }
    }
 
    public int[] getSortedArray()
    {
        if(array!=null)
        {
        	return array;
        }
        else
        {
        	return null;
        }
    }
 
    public static void main(String args[])
    {
        int array[] = {10, 7, 8, 9, 1, 5};
        int n = array.length;
        int test[]=new int[n];
        QuickSort quicksort = new QuickSort(array,n);
        quicksort.sort(0, n-1);
        test=quicksort.getSortedArray();
        for(int i = 0;i < array.length;i++)
        {
                System.out.print(test[i]+"\t");
        }
        System.out.print("\n");
    }
}
