/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'webonise' at '20/8/16 6:15 PM' with Gradle 3.0
 *
 * @author webonise, @date 20/8/16 6:15 PM
 */
package test.groovy;
import main.java.MergeSort;
import spock.lang.Specification

class MergeSortSpec extends Specification{
    def "MergeSort method Sorts input Array"() {
        setup:
			def inputArrayList=[23,43,55,123,1,67,88,100]
			int[] inputArray=[23,43,55,123,1,67,88,100]
	        MergeSort mergesort=new MergeSort(inputArray,inputArray.size())
        when:"calling the MergeSort method which sorts input"
	        mergesort.MergeSort(0,inputArray.size()-1)
			def result=new ArrayList(Arrays.asList(mergesort.getSortedArray()))
			def expectedResult=inputArrayList.sort()
        then:"Sorted array is comapred with function returned array"
        result == expectedResult
    }
	def "Merge method merges in ascending order"(){
		setup:
				def inputArrayList=[1,23,43,55,67,88,100,123]
				int[] inputArray=[23,43,55,123,1,67,88,100]
				MergeSort mergesort=new MergeSort(inputArray,inputArray.size())
				
		when: "calling merge methode which merges the input in ascending Order"
				mergesort.Merge(0,3,7);
				def result=new ArrayList(Arrays.asList(mergesort.getSortedArray()))
		
		then:"compares output of merge method with expected output"
				inputArrayList==result	
	}
	def "MergeSort do not sorts for empty array"(){
		
		setup:
				int[] inputarray=null; 
				MergeSort mergesort=new MergeSort(inputarray,0);
			
		when:"calling the MergeSort method which sorts input"
				mergesort.MergeSort(0,0);
				def result=mergesort.getSortedArray()
		then:"Sorted array is comapred with function returned array"
				result == null
	}
}
